# Configuración de Netlify para GoodPro
[build]
  publish = "dist"
  command = "npm run build"

# Redirecciones para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Headers para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Variables de entorno (configurar en Netlify dashboard)
# VITE_SUPABASE_URL = "https://xxx.supabase.co"
# VITE_SUPABASE_ANON_KEY = "eyJhbG..."